### ISSUE TITLE
pyramid install results in 500 Internal Server Error

### ISSUE THREAD

**Issue by mlechner** [lmacken/pyramid-openshift-quickstart#3]
- tried: ./openshift-quickstarter foo@bar.de mydomain pyramid pyramid

...
Adding 'mysql-5.1' to application 'pyramid'
Success
...
From git://github.com/lmacken/pyramid-openshift-quickstart
...
remote: Installed /var/lib/openshift/xxx/python-2.6/virtenv
remote: Processing dependencies for YourAppName==1.0
remote: Finished processing dependencies for YourAppName==1.0
remote: Script /var/lib/openshift/xxx/python-2.6/virtenv/bin/activate.csh cannot be made relative (it's not a normal script that starts with #!/var/lib/openshift/xxx/python-2.6/virtenv/bin/python)
remote: Making script /var/lib/openshift/xxx/python-2.6/virtenv/bin/pip relative
remote: Script /var/lib/openshift/xxx/python-2.6/virtenv/bin/activate.fish cannot be made relative (it's not a normal script that starts with #!/var/lib/openshift/xxx/python-2.6/virtenv/bin/python)
remote: Making script /var/lib/openshift/xxx/python-2.6/virtenv/bin/easy_install relative
remote: Making script /var/lib/openshift/xxx/python-2.6/virtenv/bin/easy_install-2.6 relative
remote: Making script /var/lib/openshift/xxx/python-2.6/virtenv/bin/pip-2.6 relative
remote: Running .openshift/action_hooks/build
remote: /var/lib/openshift/xxx/app-root/runtime/repo/.openshift/action_hooks/build: Zeile 9: /var/lib/openshift/xxx/pyramid/virtenv/bin/activate: Datei oder Verzeichnis nicht gefunden
remote: Symlinking static resources from pyramidapp/public
remote: /usr/lib64/python2.6/distutils/dist.py:266: UserWarning: Unknown distribution option: 'paster_plugins'
remote:   warnings.warn(msg)
remote: running develop
remote: error: can't create or remove files in install directory
remote: 
remote: The following error occurred while trying to add or remove files in the
remote: installation directory:
remote: 
remote:     [Errno 13] Permission denied: '/usr/lib/python2.6/site-packages/test-easy-install-13304.write-test'
remote: 
remote: The installation directory you specified (via --install-dir, --prefix, or
remote: the distutils default setting) was:
remote: 
remote:     /usr/lib/python2.6/site-packages/
remote: 
remote: Perhaps your account does not have write access to this directory?  If the
remote: installation directory is a system-owned directory, you may need to sign in
remote: as the administrator or "root" account.  If you do not have administrative
remote: access to this machine, you may wish to choose a different installation
remote: directory, preferably one that is listed in your PYTHONPATH environment
remote: variable.
...
remote: 
remote: For information on other options, you may wish to consult the
remote: documentation at:
remote: 
remote:   http://peak.telecommunity.com/EasyInstall.html
remote: 
remote: Please make the appropriate changes for your system and try again.
remote: 
remote: New python executable in /var/lib/openshift/xxx//python-2.6/virtenv/bin/python
remote: Installing setuptools.............done.
remote: Installing pip...............done.
remote: Running .openshift/action_hooks/deploy
remote: /var/lib/openshift/xxx/app-root/runtime/repo/.openshift/action_hooks/deploy: Zeile 9: /var/lib/openshift/xxx/pyramid/virtenv/bin/activate: Datei oder Verzeichnis nicht gefunden
remote: 
remote: 
remote: Could not find mysql database.  Please run:
remote: rhc-ctl-app -a pyramid -e add-mysql-5.1
remote: then make a sample commit (add whitespace somewhere) and re-push
remote: 
remote: 
remote: hot_deploy_added=false
remote: MySQL already running
remote: Done
remote: Running .openshift/action_hooks/post_deploy
To ssh://xxx@pyramid-mydomain.rhcloud.com/~/git/pyramid.git/
   03605bf..7991e0f  master -> master

Complete!
You can view your application at http://pyramid-mydomain.rhcloud.com
- But !! The resulting application returns a 500 Internal Server Error when opening the URL. ServerLog is:

[Tue Nov 13 09:10:59 2012] [error] [client 127.9.45.1] mod_wsgi (pid=23393): Target WSGI script '/var/lib/openshift/xxx/app-root/runtime/repo/wsgi/application' cannot be loaded as Python module.
[Tue Nov 13 09:10:59 2012] [error] [client 127.9.45.1] mod_wsgi (pid=23393): Exception occurred processing WSGI script '/var/lib/openshift/xxx/app-root/runtime/repo/wsgi/application'.
[Tue Nov 13 09:10:59 2012] [error] [client 127.9.45.1] Traceback (most recent call last):
[Tue Nov 13 09:10:59 2012] [error] [client 127.9.45.1] File "/var/lib/openshift/xxx/app-root/runtime/repo/wsgi/application", line 19, in
[Tue Nov 13 09:10:59 2012] [error] [client 127.9.45.1] from pyramid.paster import get_app
[Tue Nov 13 09:10:59 2012] [error] [client 127.9.45.1] ImportError: No module named pyramid.paster

==> python-2.6/logs/access_log-20121113-000000-EST <==

**Comment by lmacken** [comment]
Fixed in 0245040fc8

Thanks for the report!
